services:
  app:
    build:
      context: .
    ports:
      - 8010:8010
    environment:
      - TZ=Europe/Moscow
      - PYTHONUNBUFFERED=0
    volumes:
      - ${GOOGLE_CRED}:/app/google_conf.json
    command: bash -c "python3 server.py"
